export const CATEGORIES = [
  { icon: "👷", name: "Pedreiro" },
  { icon: "⚡", name: "Eletricista" },
  { icon: "🚿", name: "Encanador" },
  { icon: "🪚", name: "Marceneiro" },
  { icon: "🪣", name: "Pintor" },
  { icon: "🧹", name: "Faxineira" },
  { icon: "🧱", name: "Gesseiro" },
  { icon: "🔲", name: "Azulejista" },
  { icon: "🪵", name: "Carpinteiro" },
  { icon: "🔩", name: "Serralheiro" },
  { icon: "🪟", name: "Vidraceiro" },
  { icon: "🏠", name: "Telhadista" },
  { icon: "❄️", name: "Técnico em Ar-Condicionado" },
  { icon: "🧊", name: "Técnico em Refrigeração" },
  { icon: "🔑", name: "Chaveiro" },
  { icon: "🪴", name: "Jardineiro" },
  { icon: "🏊", name: "Piscineiro" },
  { icon: "🦟", name: "Dedetizador" },
  { icon: "🧼", name: "Empregada Doméstica" },
  { icon: "🛋️", name: "Lavador de Sofá e Estofados" },
  { icon: "🧺", name: "Lavador de Carpetes" },
  { icon: "🪛", name: "Montador de Móveis" },
  { icon: "🚚", name: "Freteiro" },
  { icon: "🚗", name: "Motorista Particular" },
  { icon: "🔧", name: "Mecânico Automotivo" },
  { icon: "🔨", name: "Funileiro" },
  { icon: "🛞", name: "Borracheiro" },
  { icon: "🪝", name: "Guincho / Reboque" },
  { icon: "🧑‍🏭", name: "Soldador" },
  { icon: "💻", name: "Técnico em Informática" },
  { icon: "📹", name: "Instalador de Câmeras" },
  { icon: "☀️", name: "Instalador de Energia Solar" },
  { icon: "📚", name: "Professor Particular" },
  { icon: "🏋️", name: "Personal Trainer" },
  { icon: "🥗", name: "Nutricionista" },
  { icon: "🧠", name: "Psicólogo" },
  { icon: "🧘", name: "Fisioterapeuta" },
  { icon: "👵", name: "Cuidador de Idosos" },
  { icon: "👶", name: "Babá" },
  { icon: "💇", name: "Cabeleireiro" },
  { icon: "💈", name: "Barbeiro" },
  { icon: "💅", name: "Manicure / Pedicure" },
  { icon: "💄", name: "Maquiador" },
  { icon: "✨", name: "Esteticista" },
  { icon: "🧵", name: "Costureira" },
  { icon: "👞", name: "Sapateiro" },
  { icon: "🧑‍🍳", name: "Cozinheiro Particular" },
  { icon: "🧁", name: "Confeiteiro" },
  { icon: "🍽️", name: "Garçom" },
  { icon: "🎧", name: "DJ" },
  { icon: "🎈", name: "Decorador de Festas" },
  { icon: "🛡️", name: "Segurança Particular" },
  { icon: "🏢", name: "Porteiro" },
  { icon: "🔦", name: "Vigilante" },
  { icon: "🚜", name: "Operador de Máquinas" },
  { icon: "🦺", name: "Técnico em Segurança do Trabalho" },
  { icon: "📐", name: "Engenheiro Civil" },
  { icon: "🏛️", name: "Arquiteto" },
  { icon: "🖼️", name: "Designer de Interiores" },
  { icon: "🗺️", name: "Topógrafo" },
  { icon: "🌾", name: "Técnico Agrícola" },
  { icon: "🐶", name: "Veterinário" },
  { icon: "🐕", name: "Adestrador de Cães" },
  { icon: "🐾", name: "Passeador de Cães" },
  { icon: "🏍️", name: "Entregador / Motoboy" },
  { icon: "📡", name: "Instalador de Antenas" },
  { icon: "🧶", name: "Tapeceiro" },
  { icon: "✨", name: "Polidor Automotivo" },
  { icon: "🧽", name: "Higienizador Automotivo" },
  { icon: "🚁", name: "Operador de Drone" },
  { icon: "🏗️", name: "Mestre de Obras" },
  { icon: "🛠️", name: "Auxiliar de Construção" },
  { icon: "🤖", name: "Técnico em Automação Residencial" },
  { icon: "🚧", name: "Instalador de Cerca Elétrica" },
  { icon: "🚪", name: "Instalador de Portão Eletrônico" },
  { icon: "🚨", name: "Técnico em Alarmes" },
  { icon: "🌳", name: "Podador de Árvores" },
  { icon: "💧", name: "Limpador de Caixa d’Água" },
  { icon: "🧗", name: "Limpador de Fachada" },
  { icon: "🎚️", name: "Operador de Som e Iluminação" },
];
